.TH apertium-tolk 1 2006-03-08 "" ""
.SH NAME
apertium-tolk \- This application is part of (
.B apertium
)
.PP
This tool is part of the apertium machine translation
architecture: \fBhttp://www.apertium.org\fR.
.SH SYNOPSIS
.B apertium
[-u] {language-pair} 
.SH DESCRIPTION
.BR apertium-tolk
is an application which provides a graphical user interface to 
the apertium machine translation system.
.PP
The different modules behind the apertium machine translation
architecture are in order:
.RE
.SH OPTIONS
.PP
.B -u
Disable marking of unknown words with the '*' character.
.PP
.B -v
Print the version
.PP
.B language-pair
The language pair: LANG1-LANG2 (for instance \fIes-ca\fR or \fIca-es\fR).
.PP
.RS
.SH SEE ALSO
.I apertium\fR(1).
.SH BUGS
Lots of...lurking in the dark and waiting for you!
.SH AUTHOR
(c) 2007-2008 Francis Tyers
